services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  T3G\SvgSanitizer\:
    resource: '../Classes/*'

  T3G\SvgSanitizer\EventListener\ResourceStorageListener:
    tags:
      - name: event.listener
        identifier: 'svg-sanitizer/resource-storage-listener-beforeFileAddedEvent'
        method: 'beforeFileAdded'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileAddedEvent
      - name: event.listener
        identifier: 'svg-sanitizer/resource-storage-listener-beforeFileReplacedEvent'
        method: 'beforeFileReplaced'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileReplacedEvent
      - name: event.listener
        identifier: 'svg-sanitizer/resource-storage-listener-afterFileContentsSet'
        method: 'afterFileContentsSet'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileContentsSetEvent
